### ISSUE TITLE
No PlatformIO project for STM32G4

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Luos_bootloader#1]
Following [this tutorial (https://docs.luos.io/pages/tutorials/luos-tools/bootloader.html#step-4-load-the-bootloader)](https://docs.luos.io/pages/tutorials/luos-tools/bootloader.html#step-4-load-the-bootloader) with some STM32G4, I couldn't find a PlatformIO project for the bootloader in `Luos_bootloader/bootloader_stm32g431kb`. ~~It turns out the app is in `Luos_bootloader_app/luos_bootloader_application_g431kb`.~~

**Comment by JeromeGalan** [comment]
@ncros3 : is it done ?

**Comment by ncros3** [comment]
Yes, it's done.
